### ISSUE TITLE
awsvpnclient not starting after the install

### ISSUE THREAD

**Issue by Andyvec** [BOPOHA/aws-rpm-packages#2]
Hi,

I have just install awsvpnclient from your repo in Fedora 36, and this is result:

```
systemctl start awsvpnclient
Failed to start awsvpnclient.service: Sending user's quota exceeded
See system logs and 'systemctl status awsvpnclient.service' for details.
systemctl status awsvpnclient.service
○ awsvpnclient.service
     Loaded: loaded (/usr/lib/systemd/system/awsvpnclient.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
```

Is there any follow step need in order to configure or finish the set-up?

Thanks in advance

**Comment by BOPOHA** [comment]
> Is there any follow step need in order to configure or finish the set-up?

there are no additional settings here


> systemctl start awsvpnclient
> Failed to start awsvpnclient.service: Sending user's quota exceeded

let me guess, you have a discrete nvidia card, right?
If so, google something like `"Sending user's quota exceeded" nvidia`

i usually use intel cards.
