### ISSUE TITLE
libva error

### ISSUE THREAD

**Issue by thePaulRichard** [BOPOHA/aws-rpm-packages#3]
Hello! When I tried to connect using awsvpnclient I get this error:

`
'libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
`
I don't know if it is relevant, but my GPU is AMD  (AMD Radeon™ RX 6600M / AMD RENOIR)

**Comment by BOPOHA** [comment]
I use intel. I don't know how nvidia or amd cards work with wayland .
You can try something like this `LIBVA_DRIVER_NAME=radeonsi awsvpnclient`
or ask Google...

**Comment by BOPOHA** [comment]
4.1.0.1523-5 does not support libva.
now workspacesclient has new versions with libva support: 4.3.0.1766 and 4.4.0.1808
