### ISSUE TITLE
[BUG] fc40 workspacesclient-wsp-2024.7.5140

### ISSUE THREAD

**Issue by claer** [BOPOHA/aws-rpm-packages#31]
**Describe the bug**

New version of WorkspacesClient-WSP requires ffmpeg-libs >= 7: 
- libavcodec.so.61(LIBAVCODEC_61)(64bit)
- libavutil.so.59(LIBAVUTIL_59)(64bit)

fc40 come with ffmpeg-libs-6.1.2 (libavcodec.so.60 and libavutil.so.58)

**Comment by BOPOHA** [comment]
@claer it will be hard to backport all the dependencies into the fc40
so, it is time to upgrade the fc 

you can check the workspacesclient-wsp 2024.7.5140-1 with fc41

**Comment by claer** [comment]
Thanks for the followup. I want to take time to reinstall from scratch for this new version. My fedora is upgraded release from release since f27, I want to clean up things before.

**Comment by claer** [comment]
@BOPOHA AWS released another version:
Version: 2024.8.5191
sha256sum: 043c4cc9c56059c88965ef02b44957696567a980d03b93666b02b5d06bcfdbe9

Once your spec file updated with that version, I could install and connect to my workspaces instance under Fedora-41
Thanks for your work!

**Comment by BOPOHA** [comment]
@claer you are welcome!
